

/*//////////////////////////////////////////////////////////////////////////////////////
////// Autogenerated by JaySvcUtil.exe http://JayData.org for more info        /////////
//////                             oData V2                                    /////////
//////////////////////////////////////////////////////////////////////////////////////*/
(function(global, $data, undefined) {

  $data.Entity.extend('ArticlesViewModel_1.articles', {
    '﻿Id': { 'key':true,'type':'Edm.String','nullable':true,'maxLength':4000 },
    'WholesalerId': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'Listprice': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'Deliverytime': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'MaxBoDays': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'Fillingrate': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'Mechanical': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'Stock': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'FrDtType': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'SortcodeId': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'GenreId': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'Artist': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'Title': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'Eancode': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'MajorId': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'OriginId': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'MediaId': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'SubmediaId': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'LabelId': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'LanguageId': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'StatuscodeId': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'Suffix': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'Infoline': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'Prefix': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'Releasedate': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'Activated': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'Units': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'Eanpref': { 'type':'Edm.String','nullable':true,'maxLength':4000 }
  });
  
  $data.Entity.extend('GenresViewModel.genres', {
    'Id': { 'key':true,'type':'Edm.String','nullable':true,'maxLength':4000 },
    'WholesalerId': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'MainGenre': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'Description': { 'type':'Edm.String','nullable':true,'maxLength':4000 }
  });
  
  $data.Entity.extend('SYS.Columns', {
    'VDBName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'SchemaName': { 'key':true,'type':'Edm.String','nullable':true,'maxLength':255 },
    'TableName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'Name': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'Position': { 'type':'Edm.Int32','nullable':false,'required':true },
    'NameInSource': { 'type':'Edm.String','nullable':true,'maxLength':255 },
    'DataType': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
    'Scale': { 'type':'Edm.Int32','nullable':false,'required':true },
    'Length': { 'type':'Edm.Int32','nullable':false,'required':true },
    'IsLengthFixed': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'SupportsSelect': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'SupportsUpdates': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'IsCaseSensitive': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'IsSigned': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'IsCurrency': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'IsAutoIncremented': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'NullType': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
    'MinRange': { 'type':'Edm.String','nullable':true,'maxLength':50 },
    'MaxRange': { 'type':'Edm.String','nullable':true,'maxLength':50 },
    'DistinctCount': { 'type':'Edm.Int32','nullable':true },
    'NullCount': { 'type':'Edm.Int32','nullable':true },
    'SearchType': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
    'Format': { 'type':'Edm.String','nullable':true,'maxLength':255 },
    'DefaultValue': { 'type':'Edm.String','nullable':true,'maxLength':255 },
    'JavaClass': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':500 },
    'Precision': { 'type':'Edm.Int32','nullable':false,'required':true },
    'CharOctetLength': { 'type':'Edm.Int32','nullable':true },
    'Radix': { 'type':'Edm.Int32','nullable':false,'required':true },
    'UID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'Description': { 'type':'Edm.String','nullable':true,'maxLength':255 },
    'OID': { 'type':'Edm.Int32','nullable':true },
    'Tables': { 'type':'SYS.Tables','inverseProperty':'Columns' },
    'DataTypes': { 'type':'SYS.DataTypes','inverseProperty':'Columns' }
  });
  
  $data.Entity.extend('SYS.DataTypes', {
    'Name': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
    'IsStandard': { 'type':'Edm.Boolean','nullable':true },
    'IsPhysical': { 'type':'Edm.Boolean','nullable':true },
    'TypeName': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
    'JavaClass': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':500 },
    'Scale': { 'type':'Edm.Int32','nullable':true },
    'TypeLength': { 'type':'Edm.Int32','nullable':false,'required':true },
    'NullType': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
    'IsSigned': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'IsAutoIncremented': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'IsCaseSensitive': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'Precision': { 'type':'Edm.Int32','nullable':false,'required':true },
    'Radix': { 'type':'Edm.Int32','nullable':true },
    'SearchType': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
    'UID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'RuntimeType': { 'type':'Edm.String','nullable':true,'maxLength':64 },
    'BaseType': { 'type':'Edm.String','nullable':true,'maxLength':64 },
    'Description': { 'type':'Edm.String','nullable':true,'maxLength':255 },
    'OID': { 'type':'Edm.Int32','nullable':true },
    'Columns': { 'type':'Array','elementType':'SYS.Columns','inverseProperty':'DataTypes' },
    'ProcedureParams': { 'type':'Array','elementType':'SYS.ProcedureParams','inverseProperty':'DataTypes' }
  });
  
  $data.Entity.extend('SYS.KeyColumns', {
    'VDBName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'SchemaName': { 'key':true,'type':'Edm.String','nullable':true,'maxLength':255 },
    'TableName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':2048 },
    'Name': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'KeyName': { 'type':'Edm.String','nullable':true,'maxLength':255 },
    'KeyType': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
    'RefKeyUID': { 'type':'Edm.String','nullable':true,'maxLength':50 },
    'UID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'Position': { 'type':'Edm.Int32','nullable':true },
    'OID': { 'type':'Edm.Int32','nullable':true },
    'Tables': { 'type':'SYS.Tables','inverseProperty':'KeyColumns' }
  });
  
  $data.Entity.extend('SYS.Keys', {
    'VDBName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'SchemaName': { 'key':true,'type':'Edm.String','nullable':true,'maxLength':255 },
    'TableName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':2048 },
    'Name': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'Description': { 'type':'Edm.String','nullable':true,'maxLength':255 },
    'NameInSource': { 'type':'Edm.String','nullable':true,'maxLength':255 },
    'Type': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
    'IsIndexed': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'RefKeyUID': { 'type':'Edm.String','nullable':true,'maxLength':50 },
    'UID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'OID': { 'type':'Edm.Int32','nullable':true },
    'Tables': { 'type':'SYS.Tables','inverseProperty':'Keys' }
  });
  
  $data.Entity.extend('SYS.ProcedureParams', {
    'VDBName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'SchemaName': { 'key':true,'type':'Edm.String','nullable':true,'maxLength':255 },
    'ProcedureName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'Name': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'DataType': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':25 },
    'Position': { 'type':'Edm.Int32','nullable':false,'required':true },
    'Type': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':100 },
    'Optional': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'Precision': { 'type':'Edm.Int32','nullable':false,'required':true },
    'TypeLength': { 'type':'Edm.Int32','nullable':false,'required':true },
    'Scale': { 'type':'Edm.Int32','nullable':false,'required':true },
    'Radix': { 'type':'Edm.Int32','nullable':false,'required':true },
    'NullType': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':10 },
    'UID': { 'type':'Edm.String','nullable':true,'maxLength':50 },
    'Description': { 'type':'Edm.String','nullable':true,'maxLength':255 },
    'OID': { 'type':'Edm.Int32','nullable':true },
    'Procedures': { 'type':'SYS.Procedures','inverseProperty':'ProcedureParams' },
    'DataTypes': { 'type':'SYS.DataTypes','inverseProperty':'ProcedureParams' }
  });
  
  $data.Entity.extend('SYS.Procedures', {
    'VDBName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'SchemaName': { 'key':true,'type':'Edm.String','nullable':true,'maxLength':255 },
    'Name': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'NameInSource': { 'type':'Edm.String','nullable':true,'maxLength':255 },
    'ReturnsResults': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'UID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'Description': { 'type':'Edm.String','nullable':true,'maxLength':255 },
    'OID': { 'type':'Edm.Int32','nullable':true },
    'ProcedureParams': { 'type':'Array','elementType':'SYS.ProcedureParams','inverseProperty':'Procedures' },
    'Schemas': { 'type':'SYS.Schemas','inverseProperty':'Procedures' }
  });
  
  $data.Entity.extend('SYS.Properties', {
    'Name': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'Value': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'UID': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'OID': { 'type':'Edm.Int32','nullable':true },
    'ClobValue': { 'type':'Edm.Binary','nullable':true }
  });
  
  $data.Entity.extend('SYS.Schemas', {
    'VDBName': { 'key':true,'type':'Edm.String','nullable':true,'maxLength':255 },
    'Name': { 'key':true,'type':'Edm.String','nullable':true,'maxLength':255 },
    'IsPhysical': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'UID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'Description': { 'type':'Edm.String','nullable':true,'maxLength':255 },
    'PrimaryMetamodelURI': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'OID': { 'type':'Edm.Int32','nullable':true },
    'Procedures': { 'type':'Array','elementType':'SYS.Procedures','inverseProperty':'Schemas' },
    'Tables': { 'type':'Array','elementType':'SYS.Tables','inverseProperty':'Schemas' }
  });
  
  $data.Entity.extend('SYS.Tables', {
    'VDBName': { 'key':true,'type':'Edm.String','nullable':true,'maxLength':255 },
    'SchemaName': { 'key':true,'type':'Edm.String','nullable':true,'maxLength':255 },
    'Name': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'Type': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':20 },
    'NameInSource': { 'type':'Edm.String','nullable':true,'maxLength':255 },
    'IsPhysical': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'SupportsUpdates': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'UID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'Cardinality': { 'type':'Edm.Int32','nullable':false,'required':true },
    'Description': { 'type':'Edm.String','nullable':true,'maxLength':255 },
    'IsSystem': { 'type':'Edm.Boolean','nullable':true },
    'IsMaterialized': { 'type':'Edm.Boolean','nullable':false,'required':true },
    'OID': { 'type':'Edm.Int32','nullable':true },
    'Columns': { 'type':'Array','elementType':'SYS.Columns','inverseProperty':'Tables' },
    'KeyColumns': { 'type':'Array','elementType':'SYS.KeyColumns','inverseProperty':'Tables' },
    'Keys': { 'type':'Array','elementType':'SYS.Keys','inverseProperty':'Tables' },
    'Schemas': { 'type':'SYS.Schemas','inverseProperty':'Tables' }
  });
  
  $data.Entity.extend('SYS.VirtualDatabases', {
    'Name': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'Version': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':50 }
  });
  
  $data.Entity.extend('SYS.getXMLSchemas_RSParam', {
    'schema': { 'type':'Edm.Binary','nullable':true }
  });
  
  $data.Entity.extend('SYSADMIN.MatViews', {
    'VDBName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'SchemaName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'Name': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'TargetSchemaName': { 'type':'Edm.String','nullable':true,'maxLength':255 },
    'TargetName': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'Valid': { 'type':'Edm.Boolean','nullable':true },
    'LoadState': { 'type':'Edm.String','nullable':true,'maxLength':255 },
    'Updated': { 'type':'Edm.DateTime','nullable':true },
    'Cardinality': { 'type':'Edm.Int32','nullable':true }
  });
  
  $data.Entity.extend('SYSADMIN.Triggers', {
    'VDBName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'SchemaName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'TableName': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'Name': { 'key':true,'type':'Edm.String','nullable':false,'required':true,'maxLength':255 },
    'TriggerType': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'TriggerEvent': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'Status': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 },
    'Body': { 'type':'Edm.Binary','nullable':true },
    'TableUID': { 'type':'Edm.String','nullable':false,'required':true,'maxLength':50 }
  });
  
  $data.Entity.extend('SYSADMIN.VDBResources', {
    'resourcePath': { 'key':true,'type':'Edm.String','nullable':true,'maxLength':255 },
    'contents': { 'type':'Edm.Binary','nullable':true }
  });
  
  $data.Entity.extend('SYSADMIN.matViewStatus_RSParam', {
    'TargetSchemaName': { 'type':'Edm.String','nullable':true,'maxLength':50 },
    'TargetName': { 'type':'Edm.String','nullable':true,'maxLength':50 },
    'Valid': { 'type':'Edm.Boolean','nullable':true },
    'LoadState': { 'type':'Edm.String','nullable':true,'maxLength':25 },
    'Updated': { 'type':'Edm.DateTime','nullable':true },
    'Cardinality': { 'type':'Edm.Int64','nullable':true },
    'LoadNumber': { 'type':'Edm.Int64','nullable':true },
    'OnErrorAction': { 'type':'Edm.String','nullable':true,'maxLength':25 }
  });
  
  $data.Entity.extend('pg_catalog.matpg_datatype', {
    'oid': { 'key':true,'type':'Edm.Int32','nullable':true },
    'typname': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'name': { 'key':true,'type':'Edm.String','nullable':true,'maxLength':4000 },
    'uid': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'typlen': { 'type':'Edm.Int16','nullable':true }
  });
  
  $data.Entity.extend('pg_catalog.matpg_relatt', {
    'attrelid': { 'type':'Edm.Int32','nullable':true },
    'attnum': { 'type':'Edm.Int16','nullable':true },
    'attname': { 'key':true,'type':'Edm.String','nullable':true,'maxLength':4000 },
    'relname': { 'key':true,'type':'Edm.String','nullable':true,'maxLength':4000 },
    'nspname': { 'key':true,'type':'Edm.String','nullable':true,'maxLength':4000 },
    'autoinc': { 'type':'Edm.Boolean','nullable':true },
    'typoid': { 'type':'Edm.Int32','nullable':true }
  });
  
  $data.Entity.extend('pg_catalog.pg_attribute', {
    'oid': { 'key':true,'type':'Edm.Int32','nullable':true },
    'attrelid': { 'type':'Edm.Int32','nullable':true },
    'attname': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'atttypid': { 'type':'Edm.Int32','nullable':true },
    'attlen': { 'type':'Edm.Int16','nullable':true },
    'attnum': { 'type':'Edm.Int16','nullable':true },
    'atttypmod': { 'type':'Edm.Int32','nullable':true },
    'attnotnull': { 'type':'Edm.Boolean','nullable':true },
    'attisdropped': { 'type':'Edm.Boolean','nullable':true },
    'atthasdef': { 'type':'Edm.Boolean','nullable':true }
  });
  
  $data.Entity.extend('pg_catalog.pg_class', {
    'oid': { 'key':true,'type':'Edm.Int32','nullable':true },
    'relname': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'relnamespace': { 'type':'Edm.Int32','nullable':true },
    'relkind': { 'type':'Edm.String','nullable':true },
    'relam': { 'type':'Edm.Int32','nullable':true },
    'reltuples': { 'type':'Edm.Single','nullable':true },
    'relpages': { 'type':'Edm.Int32','nullable':true },
    'relhasrules': { 'type':'Edm.Boolean','nullable':true },
    'relhasoids': { 'type':'Edm.Boolean','nullable':true }
  });
  
  $data.Entity.extend('pg_catalog.pg_index', {
    'oid': { 'key':true,'type':'Edm.Int32','nullable':true },
    'indexrelid': { 'type':'Edm.Int32','nullable':true },
    'indrelid': { 'type':'Edm.Int32','nullable':true },
    'indnatts': { 'type':'Edm.Int16','nullable':true },
    'indisclustered': { 'type':'Edm.Boolean','nullable':true },
    'indisunique': { 'type':'Edm.Boolean','nullable':true },
    'indisprimary': { 'type':'Edm.Boolean','nullable':true },
    'indkey': { 'type':'List(Edm.Int16)','nullable':true },
    'indexprs': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'indpred': { 'type':'Edm.String','nullable':true,'maxLength':4000 }
  });
  
  $data.Entity.extend('pg_catalog.pg_proc', {
    'oid': { 'key':true,'type':'Edm.Int32','nullable':true },
    'proname': { 'type':'Edm.String','nullable':true,'maxLength':4000 },
    'proretset': { 'type':'Edm.Boolean','nullable':true },
    'prorettype': { 'type':'Edm.Int32','nullable':true },
    'pronargs': { 'type':'Edm.Int16','nullable':true },
    'proargtypes': { 'type':'List(Edm.Int32)','nullable':true },
    'proargnames': { 'type':'List(Edm.String)','nullable':true },
    'proargmodes': { 'type':'List(Edm.String)','nullable':true },
    'proallargtypes': { 'type':'List(Edm.Int32)','nullable':true },
    'pronamespace': { 'type':'Edm.Int32','nullable':true }
  });
  
  $data.EntityContext.extend('ArticlesViewModel_1.ArticlesViewModel_1', {
    'articles': { type: $data.EntitySet, elementType: ArticlesViewModel_1.articles }
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(ArticlesViewModel_1.ArticlesViewModel_1);
  
  /*Context Instance*/
  ArticlesViewModel_1.context = new ArticlesViewModel_1.ArticlesViewModel_1( { name:'oData', oDataServiceHost: 'http://jbossdv-stbcs.rhcloud.com/odata/basplus' });
  $data.EntityContext.extend('GenresSourceModel.GenresSourceModel', {
    'invokeHttp': $data.EntityContext.generateServiceOperation({ serviceName:'invokeHttp', returnType: null, params: [{ action: 'Edm.String' },{ request: 'Edm.Binary' },{ endpoint: 'Edm.String' },{ stream: 'Edm.Boolean' },{ result: 'Edm.Binary' },{ contentType: 'Edm.String' },{ headers: 'Edm.Binary' }], method: 'POST' })
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(GenresSourceModel.GenresSourceModel);
  
  /*Context Instance*/
  GenresSourceModel.context = new GenresSourceModel.GenresSourceModel( { name:'oData', oDataServiceHost: 'http://jbossdv-stbcs.rhcloud.com/odata/basplus' });
  $data.EntityContext.extend('ArticlesSourceModel.ArticlesSourceModel', {
    'invokeHttp': $data.EntityContext.generateServiceOperation({ serviceName:'invokeHttp', returnType: null, params: [{ action: 'Edm.String' },{ request: 'Edm.Binary' },{ endpoint: 'Edm.String' },{ stream: 'Edm.Boolean' },{ result: 'Edm.Binary' },{ contentType: 'Edm.String' },{ headers: 'Edm.Binary' }], method: 'POST' })
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(ArticlesSourceModel.ArticlesSourceModel);
  
  /*Context Instance*/
  ArticlesSourceModel.context = new ArticlesSourceModel.ArticlesSourceModel( { name:'oData', oDataServiceHost: 'http://jbossdv-stbcs.rhcloud.com/odata/basplus' });
  $data.EntityContext.extend('GenresViewModel.GenresViewModel', {
    'genres': { type: $data.EntitySet, elementType: GenresViewModel.genres }
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(GenresViewModel.GenresViewModel);
  
  /*Context Instance*/
  GenresViewModel.context = new GenresViewModel.GenresViewModel( { name:'oData', oDataServiceHost: 'http://jbossdv-stbcs.rhcloud.com/odata/basplus' });
  $data.EntityContext.extend('SYS.SYS', {
    'Columns': { type: $data.EntitySet, elementType: SYS.Columns },
    'DataTypes': { type: $data.EntitySet, elementType: SYS.DataTypes },
    'KeyColumns': { type: $data.EntitySet, elementType: SYS.KeyColumns },
    'Keys': { type: $data.EntitySet, elementType: SYS.Keys },
    'ProcedureParams': { type: $data.EntitySet, elementType: SYS.ProcedureParams },
    'Procedures': { type: $data.EntitySet, elementType: SYS.Procedures },
    'Properties': { type: $data.EntitySet, elementType: SYS.Properties },
    'Schemas': { type: $data.EntitySet, elementType: SYS.Schemas },
    'Tables': { type: $data.EntitySet, elementType: SYS.Tables },
    'VirtualDatabases': { type: $data.EntitySet, elementType: SYS.VirtualDatabases },
    'getXMLSchemas': $data.EntityContext.generateServiceOperation({ serviceName:'getXMLSchemas', returnType: $data.Queryable, elementType: 'SYS.getXMLSchemas_RSParam', params: [{ document: 'Edm.String' }], method: 'GET' })
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(SYS.SYS);
  
  /*Context Instance*/
  SYS.context = new SYS.SYS( { name:'oData', oDataServiceHost: 'http://jbossdv-stbcs.rhcloud.com/odata/basplus' });
  $data.EntityContext.extend('SYSADMIN.SYSADMIN', {
    'MatViews': { type: $data.EntitySet, elementType: SYSADMIN.MatViews },
    'Triggers': { type: $data.EntitySet, elementType: SYSADMIN.Triggers },
    'VDBResources': { type: $data.EntitySet, elementType: SYSADMIN.VDBResources },
    'isLoggable': $data.EntityContext.generateServiceOperation({ serviceName:'isLoggable', returnType: null, params: [{ loggable: 'Edm.Boolean' },{ level: 'Edm.String' },{ context: 'Edm.String' }], method: 'POST' }),
    'loadMatView': $data.EntityContext.generateServiceOperation({ serviceName:'loadMatView', returnType:  'Edm.Int32' , params: [{ schemaName: 'Edm.String' },{ viewName: 'Edm.String' },{ invalidate: 'Edm.Boolean' }], method: 'GET' }),
    'logMsg': $data.EntityContext.generateServiceOperation({ serviceName:'logMsg', returnType: null, params: [{ logged: 'Edm.Boolean' },{ level: 'Edm.String' },{ context: 'Edm.String' },{ msg: 'Edm.Binary' }], method: 'POST' }),
    'matViewStatus': $data.EntityContext.generateServiceOperation({ serviceName:'matViewStatus', returnType: $data.Queryable, elementType: 'SYSADMIN.matViewStatus_RSParam', params: [{ schemaName: 'Edm.String' },{ viewName: 'Edm.String' }], method: 'GET' }),
    'refreshMatView': $data.EntityContext.generateServiceOperation({ serviceName:'refreshMatView', returnType: null, params: [{ RowsUpdated: 'Edm.Int32' },{ ViewName: 'Edm.String' },{ Invalidate: 'Edm.Boolean' }], method: 'POST' }),
    'refreshMatViewRow': $data.EntityContext.generateServiceOperation({ serviceName:'refreshMatViewRow', returnType: null, params: [{ RowsUpdated: 'Edm.Int32' },{ ViewName: 'Edm.String' },{ Key: 'Edm.Binary' },{ KeyOther: 'Edm.Binary' }], method: 'POST' }),
    'setColumnStats': $data.EntityContext.generateServiceOperation({ serviceName:'setColumnStats', returnType: null, params: [{ tableName: 'Edm.String' },{ columnName: 'Edm.String' },{ distinctCount: 'Edm.Int64' },{ nullCount: 'Edm.Int64' },{ max: 'Edm.String' },{ min: 'Edm.String' }], method: 'POST' }),
    'setProperty': $data.EntityContext.generateServiceOperation({ serviceName:'setProperty', returnType: null, params: [{ OldValue: 'Edm.Binary' },{ UID: 'Edm.String' },{ Name: 'Edm.String' },{ Value: 'Edm.Binary' }], method: 'POST' }),
    'setTableStats': $data.EntityContext.generateServiceOperation({ serviceName:'setTableStats', returnType: null, params: [{ tableName: 'Edm.String' },{ cardinality: 'Edm.Int64' }], method: 'POST' }),
    'updateMatView': $data.EntityContext.generateServiceOperation({ serviceName:'updateMatView', returnType:  'Edm.Int32' , params: [{ schemaName: 'Edm.String' },{ viewName: 'Edm.String' },{ refreshCriteria: 'Edm.String' }], method: 'GET' })
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(SYSADMIN.SYSADMIN);
  
  /*Context Instance*/
  SYSADMIN.context = new SYSADMIN.SYSADMIN( { name:'oData', oDataServiceHost: 'http://jbossdv-stbcs.rhcloud.com/odata/basplus' });
  $data.EntityContext.extend('pg_catalog.pg_catalog', {
    'matpg_datatype': { type: $data.EntitySet, elementType: pg_catalog.matpg_datatype },
    'matpg_relatt': { type: $data.EntitySet, elementType: pg_catalog.matpg_relatt },
    'pg_attribute': { type: $data.EntitySet, elementType: pg_catalog.pg_attribute },
    'pg_class': { type: $data.EntitySet, elementType: pg_catalog.pg_class },
    'pg_index': { type: $data.EntitySet, elementType: pg_catalog.pg_index },
    'pg_proc': { type: $data.EntitySet, elementType: pg_catalog.pg_proc }
  });

  $data.generatedContexts = $data.generatedContexts || [];
  $data.generatedContexts.push(pg_catalog.pg_catalog);
  
  /*Context Instance*/
  pg_catalog.context = new pg_catalog.pg_catalog( { name:'oData', oDataServiceHost: 'http://jbossdv-stbcs.rhcloud.com/odata/basplus' });

      
})(window, $data);
      
    